import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select


driver = webdriver.Chrome()
driver.get("https://demo.nopcommerce.com/")
driver.maximize_window()
driver.implicitly_wait(10)
driver.find_element(By.ID, "small-searchterms").click()
driver.find_element(By.ID, "small-searchterms").send_keys("Laptop")
driver.find_element(By.ID, "ui-id-3").click()
driver.find_element(By.ID, "add-to-cart-button-9").click()
driver.find_element(By.LINK_TEXT, "Shopping cart").click()
driver.find_element(By.ID, "termsofservice").click()
driver.find_element(By.ID, "checkout").click()
driver.implicitly_wait(10)
driver.find_element(By.XPATH, "/html/body/div[6]/div[3]/div/div/div/div[2]/div[1]/div[1]/div[3]/button[1]").click()
driver.find_element(By.ID, "BillingNewAddress_FirstName").click()
driver.find_element(By.ID, "BillingNewAddress_FirstName").send_keys("Patryk")
driver.find_element(By.ID, "BillingNewAddress_LastName").click()
driver.find_element(By.ID, "BillingNewAddress_LastName").send_keys("Prentki")
driver.find_element(By.NAME, "BillingNewAddress.Email").click()
driver.find_element(By.NAME, "BillingNewAddress.Email").send_keys("abc@gmail.com")
dropDownElement = driver.find_element(By.ID, "BillingNewAddress_CountryId")
select = Select(dropDownElement)
select.select_by_visible_text("Poland")
driver.find_element(By.NAME, "BillingNewAddress.City").click()
driver.find_element(By.NAME, "BillingNewAddress.City").send_keys("Poznan")
driver.find_element(By.NAME, "BillingNewAddress.Address1").click()
driver.find_element(By.NAME, "BillingNewAddress.Address1").send_keys("Nauka16")
driver.find_element(By.ID, "BillingNewAddress_ZipPostalCode").click()
driver.find_element(By.ID, "BillingNewAddress_ZipPostalCode").send_keys("60-60")
driver.find_element(By.ID, "BillingNewAddress_PhoneNumber").click()
driver.find_element(By.ID, "BillingNewAddress_PhoneNumber").send_keys(700890900)
driver.find_element(By.NAME, "save").click()
driver.find_element(By.XPATH, "//*[@id='shipping-method-buttons-container']/button").click()
driver.find_element(By.ID, "paymentmethod_1").click()
driver.find_element(By.ID, "paymentmethod_0").click()
driver.find_element(By.XPATH, "//*[@id=payment-method-buttons-container]/button").click()
driver.find_element(By.XPATH, "//*[@id=payment-info-buttons-container]/button").click()
driver.find_element(By.XPATH, "//*[@id=confirm-order-buttons-container]/button").click()
driver.implicitly_wait(10)
time.sleep(5)
